M48
; DRILL file {KiCad 6.0.9-8da3e8f707~116~ubuntu20.04.1} date lun 21 nov 2022 15:45:12
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2022-11-21T15:45:12-05:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,6.0.9-8da3e8f707~116~ubuntu20.04.1
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C3.200
%
G90
G05
T1
X29.0Y-86.0
X42.0Y-24.0
X83.0Y-86.0
X91.0Y-24.0
T0
M30
