M48
; DRILL file {KiCad 6.0.9-8da3e8f707~116~ubuntu20.04.1} date mer 09 nov 2022 10:55:22
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2022-11-09T10:55:22-05:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,6.0.9-8da3e8f707~116~ubuntu20.04.1
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C3.200
%
G90
G05
T1
X18.5Y-18.5
X18.5Y-53.5
X111.5Y-18.5
X111.5Y-81.5
T0
M30
