from dnn_utils.dnn_model import DnnModel

from dnn_utils.descriptor_yolo_v4 import DescriptorYoloV4, DescriptorYoloV4Prediction
from dnn_utils.face_descriptor_extractor import FaceDescriptorExtractor
from dnn_utils.pose_estimator import PoseEstimator
from dnn_utils.ttop_keyword_spotter import TTopKeywordSpotter
from dnn_utils.voice_descriptor_extractor import VoiceDescriptorExtractor
from dnn_utils.audio_descriptor_extractor import AudioDescriptorExtractor
from dnn_utils.multiclass_audio_descriptor_extractor import MulticlassAudioDescriptorExtractor
from dnn_utils.yolo_v4 import YoloV4, YoloV4Prediction
from dnn_utils.semantic_segmentation_network import SemanticSegmentationNetwork
