#ifndef IO_MAPPING_H
#define IO_MAPPING_H

const int STEWART_PLATFORM_DYNAMIXEL_COUNT = 6;
const int STEWART_PLATFORM_DYNAMIXEL_IDS[STEWART_PLATFORM_DYNAMIXEL_COUNT] = {1, 2, 3, 4, 5, 6};

const int TORSO_DYNAMIXEL_ID = 7;
const int TORSO_LIMIT_SWITCH_PIN = 2;

#endif
