from audio_descriptor.trainers.audio_descriptor_extractor_trainer import AudioDescriptorExtractorTrainer
from audio_descriptor.trainers.multiclass_audio_descriptor_extractor_trainer \
    import MulticlassAudioDescriptorExtractorTrainer
