from common.criterions.am_softmax_loss import AmSoftmaxLoss
from common.criterions.sigmoid_focal_loss import SigmoidFocalLossWithLogits, SigmoidFocalLoss
from common.criterions.triplet_loss import TripletLoss
