from common.criterions.am_softmax_loss import AmSoftmaxLoss
from common.criterions.arc_face import ArcFaceLoss
from common.criterions.jensen_shannon_divergence import JensenShannonDivergence
from common.criterions.ohem_cross_entropy_loss import OhemCrossEntropyLoss
from common.criterions.sigmoid_focal_loss import SigmoidFocalLossWithLogits, SigmoidFocalLoss
from common.criterions.softmax_focal_loss import SoftmaxFocalLoss
from common.criterions.triplet_loss import TripletLoss
