#ifndef DYNAMIXEL_CONTROL_ACTUATORS_STEWART_KINEMATICS_PARAMETERS_H
#define DYNAMIXEL_CONTROL_ACTUATORS_STEWART_KINEMATICS_PARAMETERS_H

#include "../config.h"

#include <ArduinoEigen.h>

constexpr float STEWART_SERVO_ANGLE_MIN = -0.7853981633974483f;
constexpr float STEWART_SERVO_ANGLE_MAX = 0.7853981633974483f;
constexpr float STEWART_ROD_LENGTH = 0.19107669683f;
constexpr float STEWART_HORN_LENGTH = 0.03f;
extern const Eigen::Matrix<float, STEWART_SERVO_COUNT, 1> STEWART_HORN_ORIENTATION_ANGLES;
extern const bool STEWART_IS_HORN_ORIENTATION_REVERSED[STEWART_SERVO_COUNT];
extern const Eigen::Vector3f STEWART_TOP_ANCHORS[STEWART_SERVO_COUNT];
extern const Eigen::Vector3f STEWART_BOTTOM_LINEAR_ACTUATOR_ANCHORS[STEWART_SERVO_COUNT];

extern const Eigen::Matrix<float, 6, 1> STEWART_FORWARD_KINEMATICS_X0;
extern const Eigen::Matrix<float, 6, 1> STEWART_FORWARD_KINEMATICS_MIN_BOUNDS;
extern const Eigen::Matrix<float, 6, 1> STEWART_FORWARD_KINEMATICS_MAX_BOUNDS;

#endif
