name: T-Top Scheduled Stats Extraction From GitHub

on:
    workflow_dispatch:
    push:
        branches:
            - github-stats
    schedule:
        - cron: '0 5 * * *'
jobs:
    get_stats:
        runs-on: ubuntu-latest
        steps:
            - name: Update Stats
              uses: introlab/github-stats-action@main
              with:
                  github-stats-token: ${{ secrets.STATS_TOKEN }}
                  google-application-credentials: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}
                  spreadsheet-id: ${{ secrets.SPREADSHEET_ID }}
                  github-owner-name: 'introlab'
                  github-project-name: 'github-stats-action'
