name: T-Top Scheduled Stats Extraction From GitHub

on:
    workflow_dispatch:
    push:
        branches:
            - github-stats
    schedule:
        - cron: '0 0 * * *'
jobs:
    get_stats:
        runs-on: ubuntu-latest
        steps:
            - name: Call API to get stats
              run: |
                CLONE_STATS=$(curl -L -H "Accept: application/vnd.github+json" -H "Authorization: Bearer ${{ secrets.STATS_TOKEN_FOR_GITHUB }}" -H "X-GitHub-Api-Version: 2022-11-28" https://api.github.com/repos/introlab/t-top/traffic/clones?per=day)
                PATH_STATS=$(curl -L -H "Accept: application/vnd.github+json" -H "Authorization: Bearer ${{ secrets.STATS_TOKEN_FOR_GITHUB }}" -H "X-GitHub-Api-Version: 2022-11-28" https://api.github.com/repos/introlab/t-top/traffic/popular/paths)
                REFERRERS_STATS=$(curl -L -H "Accept: application/vnd.github+json" -H "Authorization: Bearer ${{ secrets.STATS_TOKEN_FOR_GITHUB }}" -H "X-GitHub-Api-Version: 2022-11-28" https://api.github.com/repos/introlab/t-top/traffic/popular/referrers)
                VIEWS_STATS=$(curl -L -H "Accept: application/vnd.github+json" -H "Authorization: Bearer ${{ secrets.STATS_TOKEN_FOR_GITHUB }}" -H "X-GitHub-Api-Version: 2022-11-28" https://api.github.com/repos/introlab/t-top/traffic/views?per=day)

                echo "Clones : $CLONE_STATS\n"
                echo "Paths: $PATH_STATS\n"
                echo "Referrers: $REFERRERS_STATS\n"
                echo "Views: $VIEWS_STATS\n"
